### ISSUE TITLE
failed assertion at LogCabin::Server::RaftService::appendEntries

### ISSUE THREAD

**Issue by nhardt** [logcabin/logcabin#195]
````
(gdb) bt
#0  0x00007ffff6480625 in raise () from /lib64/libc.so.6
#1  0x00007ffff6481e05 in abort () from /lib64/libc.so.6
#2  0x00007ffff647974e in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff6479810 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000043dc6d in LogCabin::Server::RaftConsensus::handleAppendEntries (this=0x832190, request=..., response=...) at build/Server/RaftConsensus.cc:1373
#5  0x000000000045d531 in LogCabin::Server::RaftService::appendEntries (this=0x83aef0, rpc=...) at build/Server/RaftService.cc:84
#6  0x000000000045d2af in LogCabin::Server::RaftService::handleRPC (this=0x83aef0, rpc=...) at build/Server/RaftService.cc:44
#7  0x0000000000550bab in LogCabin::RPC::ThreadDispatchService::workerMain (this=0x83aa50) at build/RPC/ThreadDispatchService.cc:104
#8  0x0000000000554955 in std::_Mem_fn<void (LogCabin::RPC::ThreadDispatchService::*)()>::operator() (this=0xc584c8, __object=0x83aa50) at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/tr1_impl/functional:552
#9  0x00000000005548ca in std::_Bind<std::_Mem_fn<void (LogCabin::RPC::ThreadDispatchService::*)()>(LogCabin::RPC::ThreadDispatchService*)>::__call<, 0>(const std::tuple<> &, std::_Index_tuple<0>) (this=0xc584c8, __args=Traceback (most recent call last):
  File "/usr/lib64/../share/gdb/python/libstdcxx/v6/printers.py", line 262, in children
    return self._iterator (self.val)
  File "/usr/lib64/../share/gdb/python/libstdcxx/v6/printers.py", line 220, in __init__
    raise "Top of tuple tree does not consist of a single node."
TypeError: exceptions must be old-style classes or derived from BaseException, not str
std::tuple containing) at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/tr1_impl/functional:1137
#10 0x000000000055486d in std::_Bind<std::_Mem_fn<void (LogCabin::RPC::ThreadDispatchService::*)()>(LogCabin::RPC::ThreadDispatchService*)>::operator()<>(void) (this=0xc584c8) at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/tr1_impl/functional:1191
#11 0x00000000005547ae in _Impl<std::_Bind<std::_Mem_fn<void (LogCabin::RPC::ThreadDispatchService::*)()>(LogCabin::RPC::ThreadDispatchService*)> >::_M_run(void) (this=0xc584b0) at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/thread:114
#12 0x00007ffff6d32470 in ?? () from /usr/lib64/libstdc++.so.6
#13 0x00007ffff7bc79d1 in start_thread () from /lib64/libpthread.so.0
#14 0x00007ffff65368fd in clone () from /lib64/libc.so.6
(gdb) fr 4
#4  0x000000000043dc6d in LogCabin::Server::RaftConsensus::handleAppendEntries (this=0x832190, request=..., response=...) at build/Server/RaftConsensus.cc:1373
1373	build/Server/RaftConsensus.cc: No such file or directory.
	in build/Server/RaftConsensus.cc
(gdb) print index
$1 = 3623
(gdb) print commitIndex
$2 = 8532
````

This issue arose after a test that KPs all nodes a the cluster. Still digging into details.

**Comment by nhardt** [comment]
Some other data:
````
(gdb) set print object on
(gdb) set print pretty on
(gdb) print request
$3 = (const LogCabin::Server::RaftConsensus::Request &) @0x7fffde1fba90: {
  <google::protobuf::Message> = {<No data fields>},
  members of LogCabin::Protocol::Raft::AppendEntries_Request:
  static kServerIdFieldNumber = 1,
  static kTermFieldNumber = 2,
  static kPrevLogIndexFieldNumber = 3,
  static kPrevLogTermFieldNumber = 4,
  static kEntriesFieldNumber = 5,
  static kCommitIndexFieldNumber = 6,
  _unknown_fields_ = {
    fields_ = 0x0
  },
  server_id_ = 1,
  term_ = 2909,
  prev_log_index_ = 3622,
  prev_log_term_ = 3,
  entries_ = {
    <google::protobuf::internal::RepeatedPtrFieldBase> = {
      static kInitialSize = 0,
      elements_ = 0x7fffb010fce0,
      current_size_ = 5000,
      allocated_size_ = 5000,
      total_size_ = 8192
    }, <No data fields>},
  commit_index_ = 8622,
  _cached_size_ = 0,
  _has_bits_ = {47},
  static default_instance_ = 0x8333b0
}

(gdb) print leaderId
$4 = 1

(gdb) print *log
$7 = (LogCabin::Storage::SegmentedLog &) @0x838e00: {
  <LogCabin::Storage::Log> = {
    _vptr.Log = 0x81f830,
    metadata = {
      <google::protobuf::Message> = {<No data fields>},
      members of LogCabin::Protocol::RaftLogMetadata::Metadata:
      static kCurrentTermFieldNumber = 1,
      static kVotedForFieldNumber = 2,
      _unknown_fields_ = {
        fields_ = 0x0
      },
      current_term_ = 2909,
      voted_for_ = 0,
      _cached_size_ = 5,
      _has_bits_ = {3},
      static default_instance_ = 0x834e90
    }
  },
  members of LogCabin::Storage::SegmentedLog:
  encoding = LogCabin::Storage::SegmentedLog::BINARY,
  checksumAlgorithm = "CRC32",
  MAX_SEGMENT_SIZE = 8388608,
  shouldCheckInvariants = false,
  diskWriteDurationThreshold = {
    __r = 1250
  },
  metadata = {
    <google::protobuf::Message> = {<No data fields>},
    members of LogCabin::Storage::SegmentedLogMetadata::Metadata:
    static kFormatVersionFieldNumber = 4,
    static kVersionFieldNumber = 1,
    static kRaftMetadataFieldNumber = 2,
    static kEntriesStartFieldNumber = 3,
    _unknown_fields_ = {
      fields_ = 0x0
    },
    format_version_ = 1,
    version_ = 8949,
    raft_metadata_ = 0x833740,
    entries_start_ = 1,
    _cached_size_ = 14,
    _has_bits_ = {15},
    static default_instance_ = 0x83c080
  },
  dir = {
    fd = 19,
    path = "/var/lib/logcabin/server2/log/Segmented-Binary"
  },
  openSegmentFile = {
    fd = 21,
    path = "/var/lib/logcabin/server2/log/Segmented-Binary/open-2"
  },
  logStartIndex = 1,
  segmentsByStartIndex = std::map with 3 elements = {
    [1] = {
      isOpen = false,
      startIndex = 1,
      endIndex = 3600,
      bytes = 3199082,
      filename = '0' <repeats 19 times>, "1-", '0' <repeats 16 times>, "3600",
      entries = std::deque with 3600 elements = {{
          offset = 1,
          entry = {            <google::protobuf::Message> = {<No data fields>},
            members of LogCabin::Protocol::Raft::Entry:
            static kTermFieldNumber = 1,
            static kIndexFieldNumber = 5,
            static kClusterTimeFieldNumber = 6,
            static kTypeFieldNumber = 2,
            static kConfigurationFieldNumber = 3,
            static kDataFieldNumber = 4,
            _unknown_fields_ = {
              fields_ = 0x0
            },
            term_ = 1,
            index_ = 1,
            cluster_time_ = 0,
            configuration_ = 0xfcbd90,
            data_ = 0x7ffff7bbf9f8,
            type_ = 1,
            _cached_size_ = 0,
            _has_bits_ = {31},
            static default_instance_ = 0x8378d0
          }
        }, {
          offset = 54,
          entry = {
            <google::protobuf::Message> = {<No data fields>},
            members of LogCabin::Protocol::Raft::Entry:
            static kTermFieldNumber = 1,
            static kIndexFieldNumber = 5,
            static kClusterTimeFieldNumber = 6,
            static kTypeFieldNumber = 2,
            static kConfigurationFieldNumber = 3,
            static kDataFieldNumber = 4,
            _unknown_fields_ = {
              fields_ = 0x0
            },
            term_ = 2,
            index_ = 2,
            cluster_time_ = 2844,
            configuration_ = 0x0,
            data_ = 0x7ffff7bbf9f8,
            type_ = 3,
            _cached_size_ = 0,
            _has_bits_ = {15},
            static default_instance_ = 0x8378d0
          }
        },
...
        }, {
          offset = 84783,
          entry = {
            <google::protobuf::Message> = {<No data fields>},
            members of LogCabin::Protocol::Raft::Entry:
            static kTermFieldNumber = 1,
            static kIndexFieldNumber = 5,
            static kClusterTimeFieldNumber = 6,
            static kTypeFieldNumber = 2,
            static kConfigurationFieldNumber = 3,
            static kDataFieldNumber = 4,
            _unknown_fields_ = {
              fields_ = 0x0
            },
            term_ = 17,
            index_ = 3822,
            cluster_time_ = 1720723788267,
            configuration_ = 0x0,
            data_ = 0x7fffbc189310,
            type_ = 2,
            _cached_size_ = 0,
            _has_bits_ = {47},
            static default_instance_ = 0x8378d0
          }
        }...}
    }
  },
  totalClosedSegmentBytes = 3201017,
  preparedSegments = {
    quietForUnitTests = false,
    mutex = {
      m = {
        _M_mutex = {
          __data = {
            __lock = 0,
            __count = 0,
            __owner = 0,
            __nusers = 1,
            __kind = 0,
            __spins = 0,
            __list = {
              __prev = 0x0,
              __next = 0x0
            }
          },
          __size = '\000' <repeats 12 times>, "\001", '\000' <repeats 26 times>,
          __align = 0
        }
      },
      callback = {
        <std::_Maybe_unary_or_binary_function<void>> = {<No data fields>},
        <std::_Function_base> = {
          static _M_max_size = 16,
          static _M_max_align = 8,
          _M_functor = {
            _M_unused = {
              _M_object = 0x837660,
              _M_const_object = 0x837660,
              _M_function_pointer = 0x837660,
              _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class *)) 0x837660, this adjustment 8621312
            },
            _M_pod_data = "`v\203\000\000\000\000\000\000\215\203\000\000\000\000"
          },
          _M_manager = 0
        },
        members of std::function<void()>:
        _M_invoker = 0
      }
    },
    consumed = {
      cv = {
        __data = {
          __lock = 0,
          __futex = 3,
          __total_seq = 2,
          __wakeup_seq = 1,
          __woken_seq = 1,
          __mutex = 0x838ef8,
          __nwaiters = 3,
          __broadcast_seq = 0
        },
        __size = "\000\000\000\000\003\000\000\000\002\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\370\216\203\000\000\000\000\000\003\000\000\000\000\000\000",
        __align = 12884901888
      },
      callback = {
        <std::_Maybe_unary_or_binary_function<void>> = {<No data fields>},
        <std::_Function_base> = {
          static _M_max_size = 16,
          static _M_max_align = 8,
---Type <return> to continue, or q <return> to quit---
          _M_functor = {
            _M_unused = {
              _M_object = 0x0,
              _M_const_object = 0x0,
              _M_function_pointer = 0,
              _M_member_pointer = NULL
            },
            _M_pod_data = "\000\000\000\000\000\000\000\000a\b\000\000\000\000\000"
          },
          _M_manager = 0
        },
        members of std::function<void()>:
        _M_invoker = 0x835eb0
      },
      notificationCount = {
        <std::__atomic2::__atomic_base<unsigned long>> = {
          _M_i = 2
        }, <No data fields>},
      lastWaitUntil = {
        __d = {
          __r = 0
        }
      }
    },
    produced = {
      cv = {
        __data = {
          __lock = 0,
          __futex = 0,
          __total_seq = 0,
          __wakeup_seq = 0,
          __woken_seq = 0,
          __mutex = 0x0,
          __nwaiters = 1,
          __broadcast_seq = 0
        },
        __size = '\000' <repeats 40 times>, "\001\000\000\000\000\000\000",
        __align = 0
      },
      callback = {
        <std::_Maybe_unary_or_binary_function<void>> = {<No data fields>},
        <std::_Function_base> = {
          static _M_max_size = 16,
          static _M_max_align = 8,
          _M_functor = {
            _M_unused = {
              _M_object = 0x544f485300,
              _M_const_object = 0x544f485300,
              _M_function_pointer = 0x544f485300,
              _M_member_pointer = (void (std::_Undefined_class::*)(std::_Undefined_class *)) 0x544f485300, this adjustment 2049
            },
            _M_pod_data = "\000SHOT\000\000\000\001\b\000\000\000\000\000"
          },
          _M_manager = 0
        },
        members of std::function<void()>:
        _M_invoker = 0x8323c0
      },
      notificationCount = {
        <std::__atomic2::__atomic_base<unsigned long>> = {
          _M_i = 5
        }, <No data fields>},
      lastWaitUntil = {
        __d = {
          __r = 0
        }
      }
    },
    exiting = false,
    demanded = 0,
    filenameCounter = 5,
    openSegments = std::deque with 3 elements = {{
        first = "open-3",
        second = {
          fd = 22,
          path = "/var/lib/logcabin/server2/log/Segmented-Binary/open-3"
        }
      }, {
        first = "open-4",
        second = {
          fd = 24,
          path = "/var/lib/logcabin/server2/log/Segmented-Binary/open-4"
        }
      }, {
        first = "open-5",
        second = {
          fd = 20,
          path = "/var/lib/logcabin/server2/log/Segmented-Binary/open-5"
        }
      }}
  },
  currentSync = std::tuple containing = {
    [1] = ,
    [2] = {
      <std::default_delete<LogCabin::Storage::SegmentedLog::Sync>> = {<No data fields>}, <No data fields>}
  },
  metadataWriteNanos = {
    count = 5,
    ewma2 = 64917128.4375,
    ewma4 = 74036643.48046875,
    exceptionalCount = 0,
    last = 52809333,
    lastExceptional = std::deque with 0 elements,
    max = 120278610,
    min = 47375188,
    sum = 368021394,
    sumSquares = 30753718423622462
  },
  filesystemOpsNanos = {
    count = 2,
    ewma2 = 51420404.5,
    ewma4 = 57058014.25,
    exceptionalCount = 0,
    last = 40145185,
    lastExceptional = std::deque with 0 elements,
    max = 62695624,
    min = 40145185,
    sum = 102840809,
    sumSquares = 5542377147433601
  },
  segmentPreparer = {
    _M_id = {
      _M_thread = 140737322907392
    }
  }
}
````

**Comment by nhardt** [comment]
This might be interesting.

````
[root@node ~ 16:48:16 ]# scdoall 'ls /var/lib/logcabin/*/log/*/'
Running (ls /var/lib/logcabin/*/log/*/) 192.168.8.21
    00000000000000000001-00000000000000000001
    00000000000000000002-00000000000000003600
    00000000000000003601-00000000000000009213
    metadata1
    metadata2
    open-1
    open-2
    open-3
    open-4
Running (ls /var/lib/logcabin/*/log/*/) 192.168.8.22
    00000000000000000001-00000000000000008533
    metadata1
    metadata2
    open-1
    open-2
    open-3
    open-4
Running (ls /var/lib/logcabin/*/log/*/) 192.168.8.23
    00000000000000000001-00000000000000003600
    00000000000000003601-00000000000000003622
    metadata1
    metadata2
    open-2
    open-3
    open-4
    open-5
````

**Comment by ongardie** [comment]
Ouch. Any luck getting to the root of this one, @nhardt?

**Comment by nhardt** [comment]
Oh yeah, I think I did get to the bottom of it. Going to close this one as shenanigans. There was an incomplete reset of some nodes resulting in two nodes using the same server id, which I didn't track down to how that could cause this, but it's definitely an invalid use case!

**Comment by ongardie** [comment]
Ha, ok, I can sleep soundly now.
