### ISSUE TITLE
connecting client to bogus name fails poorly

### ISSUE THREAD

**Issue by ongardie** [logcabin/logcabin#39]
ran client with bogus DNS name
```
ongaro@rcmaster:~/logcabin:master$ bt build/Examples/WriteLatency 
warning: GDB: Failed to set controlling terminal: Operation not permitted
[Thread debugging using libthread_db enabled]
1352419362.220719 RPC/MessageSocket.cc:219 in read() ERROR[24466:thread 1]: Error while reading from socket: Transport endpoint is not connected. Exiting...

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6dc5700 (LWP 24469)]
0x00000034a6a32885 in raise () from /lib64/libc.so.6
#0  0x00000034a6a32885 in raise () from /lib64/libc.so.6
#1  0x00000034a6a34065 in abort () from /lib64/libc.so.6
#2  0x000000000044d5c7 in LogCabin::RPC::MessageSocket::read (this=0x68bb80, buf=0x68bb98, maxBytes=12) at build/RPC/MessageSocket.cc:219
#3  0x000000000044d282 in LogCabin::RPC::MessageSocket::readable (this=0x68bb80) at build/RPC/MessageSocket.cc:158
#4  0x000000000044cded in LogCabin::RPC::MessageSocket::RawSocket::handleFileEvent (this=0x68bc38, events=1) at build/RPC/MessageSocket.cc:72
#5  0x00000000004503ed in LogCabin::Event::(anonymous namespace)::onFileEventFired (fd=11, libEventEvents=2, file=0x68bc38) at build/Event/File.cc:71
#6  0x00007ffff73f141c in event_process_active_single_queue (base=0x68cfa0, flags=0) at event.c:1340
#7  event_process_active (base=0x68cfa0, flags=0) at event.c:1407
#8  event_base_loop (base=0x68cfa0, flags=0) at event.c:1604
#9  0x0000000000450f3e in LogCabin::Event::Loop::runForever (this=0x691758) at build/Event/Loop.cc:167
#10 0x0000000000415503 in std::_Mem_fn<void (LogCabin::Event::Loop::*)()>::operator() (this=0x68c0c8, __object=0x691758)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/tr1_impl/functional:552
#11 0x0000000000415478 in std::_Bind<std::_Mem_fn<void (LogCabin::Event::Loop::*)()>(LogCabin::Event::Loop*)>::__call<, 0>(const std::tuple<> &, std::_Index_tuple<0>) (this=0x68c0c8, __args=Traceback (most recent call last):
  File "/usr/lib64/../share/gdb/python/libstdcxx/v6/printers.py", line 262, in children
    return self._iterator (self.val)
  File "/usr/lib64/../share/gdb/python/libstdcxx/v6/printers.py", line 220, in __init__
    raise "Top of tuple tree does not consist of a single node."
TypeError: exceptions must be old-style classes or derived from BaseException, not str
std::tuple containing) at /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/tr1_impl/functional:1137
#12 0x0000000000415415 in std::_Bind<std::_Mem_fn<void (LogCabin::Event::Loop::*)()>(LogCabin::Event::Loop*)>::operator()<>(void) (this=0x68c0c8)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/tr1_impl/functional:1191
#13 0x0000000000415356 in _Impl<std::_Bind<std::_Mem_fn<void (LogCabin::Event::Loop::*)()>(LogCabin::Event::Loop*)> >::_M_run(void) (this=0x68c0b0)
    at /usr/lib/gcc/x86_64-redhat-linux/4.4.6/../../../../include/c++/4.4.6/thread:114
#14 0x0000003d3bab6490 in ?? () from /usr/lib64/libstdc++.so.6
#15 0x00000034a72077f1 in start_thread () from /lib64/libpthread.so.0
#16 0x00000034a6ae592d in clone () from /lib64/libc.so.6
```

**Comment by ongardie** [comment]
Nope, it spins forever now, as expected. Invalid.
